<a href="https://colab.research.google.com/github/LucasPequenoSterzeck/Machine_Learning_LPS/blob/main/Misc/PyTorch_Test_EURUSD_h.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.linear_model import LogisticRegression

# Dados de treinamento
X_train = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y_train = np.array([0, 1, 0, 1])

# Criação do modelo de regressão logística
model = LogisticRegression()

# Treinamento do modelo
model.fit(X_train, y_train)

# Dados de teste
X_test = np.array([[2, 3], [4, 5]])

# Previsões
predictions = model.predict(X_test)

# Exibindo as previsões
for pred in predictions:
    print("Evento" if pred == 1 else "Não evento")

In [6]:
import pandas as pd

df = pd.read_excel(r'/content/base_teste_1h.xlsx')

In [8]:
df.dropna(subset='STATUS', inplace=True)
df.head()

,DATA,ID,CLOSE,C-1,C-2,C-3,C-4,C-5,C-6,C-7,...,ST45,ST46,ST47,ST48,C0[8],C0[20],C0[40],C1[8],C1[20],C1[40]
48,2007-06-28 00:00:00,49,134540,134540,134542.0,134507.0,134514.0,134475.0,134435.0,134409.0,...,1.0,1.0,1.0,1.0,3.0,9.0,21.0,5.0,11.0,19.0
49,2007-06-28 01:00:00,50,134542,134540,134540.0,134542.0,134507.0,134514.0,134475.0,134435.0,...,1.0,1.0,1.0,1.0,3.0,8.0,20.0,5.0,12.0,20.0
50,2007-06-28 02:00:00,51,134575,134542,134540.0,134540.0,134542.0,134507.0,134514.0,134475.0,...,0.0,1.0,1.0,1.0,3.0,7.0,20.0,5.0,13.0,20.0
51,2007-06-28 03:00:00,52,134615,134575,134542.0,134540.0,134540.0,134542.0,134507.0,134514.0,...,1.0,0.0,1.0,1.0,3.0,6.0,19.0,5.0,14.0,21.0
52,2007-06-28 04:00:00,53,134564,134615,134575.0,134542.0,134540.0,134540.0,134542.0,134507.0,...,1.0,1.0,0.0,1.0,4.0,6.0,20.0,4.0,14.0,20.0

In [9]:
df.drop(columns=['DATA','ID'], inplace=True)

In [13]:
print(df.shape)
df.head()

(99951, 115)

,CLOSE,C-1,C-2,C-3,C-4,C-5,C-6,C-7,C-8,C-9,...,ST45,ST46,ST47,ST48,C0[8],C0[20],C0[40],C1[8],C1[20],C1[40]
48,134540,134540,134542.0,134507.0,134514.0,134475.0,134435.0,134409.0,134399.0,134317.0,...,1.0,1.0,1.0,1.0,3.0,9.0,21.0,5.0,11.0,19.0
49,134542,134540,134540.0,134542.0,134507.0,134514.0,134475.0,134435.0,134409.0,134399.0,...,1.0,1.0,1.0,1.0,3.0,8.0,20.0,5.0,12.0,20.0
50,134575,134542,134540.0,134540.0,134542.0,134507.0,134514.0,134475.0,134435.0,134409.0,...,0.0,1.0,1.0,1.0,3.0,7.0,20.0,5.0,13.0,20.0
51,134615,134575,134542.0,134540.0,134540.0,134542.0,134507.0,134514.0,134475.0,134435.0,...,1.0,0.0,1.0,1.0,3.0,6.0,19.0,5.0,14.0,21.0
52,134564,134615,134575.0,134542.0,134540.0,134540.0,134542.0,134507.0,134514.0,134475.0,...,1.0,1.0,0.0,1.0,4.0,6.0,20.0,4.0,14.0,20.0

In [28]:
df[60000:]

,CLOSE,C-1,C-2,C-3,C-4,C-5,C-6,C-7,C-8,C-9,...,ST45,ST46,ST47,ST48,C0[8],C0[20],C0[40],C1[8],C1[20],C1[40]
60048,107757,107878,108024.0,108057.0,108174.0,108144.0,108043.0,108110.0,108098.0,108152.0,...,0.0,1.0,0.0,1.0,5.0,10.0,26.0,3.0,10.0,14.0
60049,107647,107757,107878.0,108024.0,108057.0,108174.0,108144.0,108043.0,108110.0,108098.0,...,1.0,0.0,1.0,0.0,6.0,10.0,26.0,2.0,10.0,14.0
60050,107625,107647,107757.0,107878.0,108024.0,108057.0,108174.0,108144.0,108043.0,108110.0,...,0.0,1.0,0.0,1.0,6.0,11.0,26.0,2.0,9.0,14.0
60051,107578,107625,107647.0,107757.0,107878.0,108024.0,108057.0,108174.0,108144.0,108043.0,...,0.0,0.0,1.0,0.0,7.0,12.0,26.0,1.0,8.0,14.0
60052,107614,107578,107625.0,107647.0,107757.0,107878.0,108024.0,108057.0,108174.0,108144.0,...,1.0,0.0,0.0,1.0,7.0,11.0,25.0,1.0,9.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99994,109190,109102,109144.0,108969.0,108535.0,108533.0,108456.0,108388.0,108563.0,108639.0,...,0.0,1.0,1.0,1.0,2.0,8.0,19.0,6.0,12.0,21.0
99995,109182,109190,109102.0,109144.0,108969.0,108535.0,108533.0,108456.0,108388.0,108563.0,...,0.0,0.0,1.0,1.0,2.0,8.0,19.0,6.0,12.0,21.0
99996,109116,109182,109190.0,109102.0,109144.0,108969.0,108535.0,108533.0,108456.0,108388.0,...,1.0,0.0,0.0,1.0,3.0,9.0,19.0,5.0,11.0,21.0
99997,109108,109116,109182.0,109190.0,109102.0,109144.0,108969.0,108535.0,108533.0,108456.0,...,1.0,1.0,0.0,0.0,4.0,10.0,19.0,4.0,10.0,21.0
99998,109129,109108,109116.0,109182.0,109190.0,109102.0,109144.0,108969.0,108535.0,108533.0,...,1.0,1.0,1.0,0.0,4.0,10.0,18.0,4.0,10.0,22.0

In [30]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from sklearn.model_selection import train_test_split

# Dados de treinamento
X = df[60000:].drop(columns='STATUS')
y = df[60000:].STATUS

# Dividir os dados em treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=42)

# Converter os dados para tensores do PyTorch
X_train = torch.tensor(X_train.values, dtype=torch.float32)
y_train = torch.tensor(y_train.values, dtype=torch.float32)
X_test = torch.tensor(X_test.values, dtype=torch.float32)

In [35]:
print(type(X_train))

<class 'torch.Tensor'>

In [ ]:
# Definir a arquitetura da rede neural
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.fc1 = nn.Linear(114, 64)
        self.fc3 = nn.Linear(64, 248)
        self.fc4 = nn.Linear(248, 248)
        self.fc5 = nn.Linear(248, 114)
        self.fc6 = nn.Linear(114, 64)
        self.fc7 = nn.Linear(64, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.fc1(x)
        x = torch.relu(x)
        x = self.fc3(x)
        x = torch.relu(x)
        x = self.fc4(x)
        x = torch.relu(x)
        x = self.fc5(x)
        x = torch.relu(x)
        x = self.fc6(x)
        x = torch.relu(x)
        x = self.fc7(x)
        x = self.sigmoid(x)
        return x

# Instanciar a rede neural
model = NeuralNetwork()

# Definir função de perda e otimizador
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.0001)

# Treinamento da rede neural
num_epochs = 100
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(X_train)
    loss = criterion(outputs.squeeze(), y_train)

    # Backward pass e otimização
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Printando a loss a cada 10 epochs
    if (epoch+1) % 10 == 0:
        print(f'Epoch {epoch+1}/{num_epochs}, Loss: {loss.item()}')

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, TensorDataset

# Dados de treinamento
X = df[60000:].drop(columns='STATUS')
y = df[60000:].STATUS

# Dividir os dados em treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=42)

# Converter os dados para tensores do PyTorch
X_train = torch.tensor(X_train.values, dtype=torch.float32)
y_train = torch.tensor(y_train.values, dtype=torch.float32)
X_test = torch.tensor(X_test.values, dtype=torch.float32)

# Criar DataLoader para os dados de treinamento em batches
train_dataset = TensorDataset(X_train, y_train)
train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)

# Definir a arquitetura da rede neural
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.fc1 = nn.Linear(114, 64)
        self.fc3 = nn.Linear(64, 248)
        self.fc4 = nn.Linear(248, 248)
        self.fc5 = nn.Linear(248, 114)
        self.fc6 = nn.Linear(114, 64)
        self.fc7 = nn.Linear(64, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.fc1(x)
        x = torch.relu(x)
        x = self.fc3(x)
        x = torch.relu(x)
        x = self.fc4(x)
        x = torch.relu(x)
        x = self.fc5(x)
        x = torch.relu(x)
        x = self.fc6(x)
        x = torch.relu(x)
        x = self.fc7(x)
        x = self.sigmoid(x)
        return x

# Instanciar a rede neural
model = NeuralNetwork()

# Definir função de perda e otimizador
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.005)

# Treinamento da rede neural
num_epochs = 10000
for epoch in range(num_epochs):
    running_loss = 0.0
    for i, (inputs, labels) in enumerate(train_loader):
        # Forward pass
        outputs = model(inputs)
        loss = criterion(outputs.squeeze(), labels)

        # Backward pass e otimização
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    # Printando a loss média a cada 10 batches
    if (epoch+1) % 10 == 0:
        average_loss = running_loss / len(train_loader)
        print(f'Epoch {epoch+1}/{num_epochs}, Loss: {average_loss}')

Epoch 10/10000, Loss: 49.97078153822157
Epoch 20/10000, Loss: 49.96313292891891
Epoch 30/10000, Loss: 49.96823199750598
Epoch 40/10000, Loss: 49.945286195286194
Epoch 50/10000, Loss: 49.955484332460344
Epoch 60/10000, Loss: 49.955484332460344
Epoch 70/10000, Loss: 49.975880606808644
Epoch 80/10000, Loss: 49.965682469634494
Epoch 90/10000, Loss: 49.95293479174476
Epoch 100/10000, Loss: 49.96823199750598
Epoch 110/10000, Loss: 49.98352920326721
Epoch 120/10000, Loss: 49.95038526387327
Epoch 130/10000, Loss: 49.96313292891891
Epoch 140/10000, Loss: 49.96058340104742
Epoch 150/10000, Loss: 49.965682469634494
Epoch 160/10000, Loss: 49.96058340104742
Epoch 170/10000, Loss: 49.945286195286194
Epoch 180/10000, Loss: 49.96058340104742
Epoch 190/10000, Loss: 49.97843013468013
Epoch 200/10000, Loss: 49.955484332460344
Epoch 210/10000, Loss: 49.95038526387327
Epoch 220/10000, Loss: 49.98352920326721
Epoch 230/10000, Loss: 49.975880606808644
Epoch 240/10000, Loss: 49.945286195286194
Epoch 250/10000, Loss: 49.95803386033183
Epoch 260/10000, Loss: 49.95803386033183
Epoch 270/10000, Loss: 49.95038526387327
Epoch 280/10000, Loss: 49.975880606808644
Epoch 290/10000, Loss: 49.95038526387327
Epoch 300/10000, Loss: 49.97078153822157
Epoch 310/10000, Loss: 49.97843013468013
Epoch 320/10000, Loss: 49.95293479174476
Epoch 330/10000, Loss: 49.97843013468013
Epoch 340/10000, Loss: 49.955484332460344
Epoch 350/10000, Loss: 49.95293479174476
Epoch 360/10000, Loss: 49.95038526387327
Epoch 370/10000, Loss: 49.96823199750598
Epoch 380/10000, Loss: 49.95293479174476
Epoch 390/10000, Loss: 49.937637598827635
Epoch 400/10000, Loss: 49.97333106609306
Epoch 410/10000, Loss: 49.945286195286194
Epoch 420/10000, Loss: 49.95293479174476
Epoch 430/10000, Loss: 49.95293479174476
Epoch 440/10000, Loss: 49.975880606808644
Epoch 450/10000, Loss: 49.955484332460344
Epoch 460/10000, Loss: 49.97078153822157
Epoch 470/10000, Loss: 49.96823199750598
Epoch 480/10000, Loss: 49.975880606808644
Epoch 490/10000, Loss: 49.965682469634494
Epoch 500/10000, Loss: 49.95803386033183
Epoch 510/10000, Loss: 49.97078153822157
Epoch 520/10000, Loss: 49.975880606808644
Epoch 530/10000, Loss: 49.96823199750598
Epoch 540/10000, Loss: 49.97333106609306
Epoch 550/10000, Loss: 49.965682469634494
Epoch 560/10000, Loss: 49.95293479174476
Epoch 570/10000, Loss: 49.94783572315768
Epoch 580/10000, Loss: 49.955484332460344
Epoch 590/10000, Loss: 49.965682469634494
Epoch 600/10000, Loss: 49.965682469634494
Epoch 610/10000, Loss: 49.94018712669912
Epoch 620/10000, Loss: 49.945286195286194
Epoch 630/10000, Loss: 49.975880606808644
Epoch 640/10000, Loss: 49.96058340104742
Epoch 650/10000, Loss: 49.95038526387327
Epoch 660/10000, Loss: 49.955484332460344
Epoch 670/10000, Loss: 49.95803386033183
Epoch 680/10000, Loss: 49.955484332460344
Epoch 690/10000, Loss: 49.96058340104742
Epoch 700/10000, Loss: 49.96058340104742
Epoch 710/10000, Loss: 49.975880606808644
Epoch 720/10000, Loss: 49.975880606808644
Epoch 730/10000, Loss: 49.95293479174476
Epoch 740/10000, Loss: 49.95293479174476
Epoch 750/10000, Loss: 49.955484332460344
Epoch 760/10000, Loss: 49.96058340104742
Epoch 770/10000, Loss: 49.97843013468013
Epoch 780/10000, Loss: 49.96313292891891
Epoch 790/10000, Loss: 49.96823199750598
Epoch 800/10000, Loss: 49.975880606808644
Epoch 810/10000, Loss: 49.95038526387327
Epoch 820/10000, Loss: 49.97078153822157
Epoch 830/10000, Loss: 49.94018712669912
Epoch 840/10000, Loss: 49.94018712669912
Epoch 850/10000, Loss: 49.94783572315768
Epoch 860/10000, Loss: 49.95038526387327
Epoch 870/10000, Loss: 49.96823199750598
Epoch 880/10000, Loss: 49.96058340104742
Epoch 890/10000, Loss: 49.945286195286194
Epoch 900/10000, Loss: 49.94018712669912
Epoch 910/10000, Loss: 49.965682469634494
Epoch 920/10000, Loss: 49.96058340104742
Epoch 930/10000, Loss: 49.95293479174476
Epoch 940/10000, Loss: 49.95803386033183
Epoch 950/10000, Loss: 49.94783572315768
Epoch 960/10000, Loss: 49.97333106609306
Epoch 970/10000, Loss: 49.95803386033183
Epoch 980/10000, Loss: 49.980979662551626
Epoch 990/10000, Loss: 49.97333106609306
Epoch 1000/10000, Loss: 49.955484332460344
Epoch 1010/10000, Loss: 49.97843013468013
Epoch 1020/10000, Loss: 49.95803386033183
Epoch 1030/10000, Loss: 49.96313292891891
Epoch 1040/10000, Loss: 49.95803386033183
Epoch 1050/10000, Loss: 49.980979662551626
Epoch 1060/10000, Loss: 49.94273666741471
Epoch 1070/10000, Loss: 49.96823199750598
Epoch 1080/10000, Loss: 49.96058340104742
Epoch 1090/10000, Loss: 49.97843013468013
Epoch 1100/10000, Loss: 49.98862827185428
Epoch 1110/10000, Loss: 49.95803386033183
Epoch 1120/10000, Loss: 49.965682469634494
Epoch 1130/10000, Loss: 49.965682469634494
Epoch 1140/10000, Loss: 49.95293479174476
Epoch 1150/10000, Loss: 49.955484332460344
Epoch 1160/10000, Loss: 49.96823199750598
Epoch 1170/10000, Loss: 49.97078153822157
Epoch 1180/10000, Loss: 49.937637598827635
Epoch 1190/10000, Loss: 49.96823199750598
Epoch 1200/10000, Loss: 49.95803386033183
Epoch 1210/10000, Loss: 49.96823199750598
Epoch 1220/10000, Loss: 49.97333106609306
Epoch 1230/10000, Loss: 49.97078153822157
Epoch 1240/10000, Loss: 49.95803386033183
Epoch 1250/10000, Loss: 49.96313292891891
Epoch 1260/10000, Loss: 49.96058340104742
Epoch 1270/10000, Loss: 49.96823199750598
Epoch 1280/10000, Loss: 49.96823199750598
Epoch 1290/10000, Loss: 49.955484332460344
Epoch 1300/10000, Loss: 49.965682469634494
Epoch 1310/10000, Loss: 49.96823199750598
Epoch 1320/10000, Loss: 49.965682469634494
Epoch 1330/10000, Loss: 49.96058340104742
Epoch 1340/10000, Loss: 49.980979662551626
Epoch 1350/10000, Loss: 49.96313292891891
Epoch 1360/10000, Loss: 49.94783572315768
Epoch 1370/10000, Loss: 49.96058340104742
Epoch 1380/10000, Loss: 49.96313292891891
Epoch 1390/10000, Loss: 49.97333106609306
Epoch 1400/10000, Loss: 49.95293479174476
Epoch 1410/10000, Loss: 49.965682469634494
Epoch 1420/10000, Loss: 49.97078153822157
Epoch 1430/10000, Loss: 49.97333106609306
Epoch 1440/10000, Loss: 49.97843013468013
Epoch 1450/10000, Loss: 49.955484332460344
Epoch 1460/10000, Loss: 49.965682469634494
Epoch 1470/10000, Loss: 49.955484332460344
Epoch 1480/10000, Loss: 49.94783572315768
Epoch 1490/10000, Loss: 49.95803386033183
Epoch 1510/10000, Loss: 49.96313292891891
Epoch 1520/10000, Loss: 49.96313292891891
Epoch 1530/10000, Loss: 49.97843013468013
Epoch 1540/10000, Loss: 49.95803386033183
Epoch 1550/10000, Loss: 49.955484332460344
Epoch 1560/10000, Loss: 49.95803386033183
Epoch 1570/10000, Loss: 49.95293479174476
Epoch 1580/10000, Loss: 49.955484332460344
Epoch 1590/10000, Loss: 49.96823199750598
Epoch 1600/10000, Loss: 49.96313292891891
Epoch 1610/10000, Loss: 49.95038526387327
Epoch 1620/10000, Loss: 49.96823199750598
Epoch 1630/10000, Loss: 49.96313292891891
Epoch 1640/10000, Loss: 49.97078153822157
Epoch 1650/10000, Loss: 49.96313292891891
Epoch 1660/10000, Loss: 49.95803386033183
Epoch 1670/10000, Loss: 49.955484332460344
Epoch 1680/10000, Loss: 49.96313292891891
Epoch 1690/10000, Loss: 49.97078153822157
Epoch 1700/10000, Loss: 49.94273666741471
Epoch 1710/10000, Loss: 49.980979662551626
Epoch 1720/10000, Loss: 49.97078153822157
Epoch 1730/10000, Loss: 49.95803386033183
Epoch 1740/10000, Loss: 49.97333106609306
Epoch 1750/10000, Loss: 49.96313292891891
Epoch 1760/10000, Loss: 49.980979662551626
Epoch 1770/10000, Loss: 49.97333106609306
Epoch 1780/10000, Loss: 49.96058340104742
Epoch 1790/10000, Loss: 49.97333106609306
Epoch 1800/10000, Loss: 49.965682469634494
Epoch 1810/10000, Loss: 49.95803386033183
Epoch 1820/10000, Loss: 49.955484332460344
Epoch 1830/10000, Loss: 49.965682469634494
Epoch 1840/10000, Loss: 49.97333106609306
Epoch 1850/10000, Loss: 49.94783572315768
Epoch 1860/10000, Loss: 49.95803386033183
Epoch 1870/10000, Loss: 49.95803386033183
Epoch 1880/10000, Loss: 49.937637598827635
Epoch 1890/10000, Loss: 49.96313292891891
Epoch 1900/10000, Loss: 49.955484332460344
Epoch 1910/10000, Loss: 49.97078153822157
Epoch 1920/10000, Loss: 49.986078743982794
Epoch 1930/10000, Loss: 49.96313292891891
Epoch 1940/10000, Loss: 49.96823199750598
Epoch 1950/10000, Loss: 49.975880606808644
Epoch 1960/10000, Loss: 49.95038526387327
Epoch 1970/10000, Loss: 49.955484332460344
Epoch 1980/10000, Loss: 49.96313292891891
Epoch 1990/10000, Loss: 49.94273666741471
Epoch 2000/10000, Loss: 49.965682469634494
Epoch 2010/10000, Loss: 49.95293479174476
Epoch 2020/10000, Loss: 49.965682469634494
Epoch 2030/10000, Loss: 49.95293479174476
Epoch 2040/10000, Loss: 49.95038526387327
Epoch 2050/10000, Loss: 49.97078153822157
Epoch 2060/10000, Loss: 49.96313292891891
Epoch 2070/10000, Loss: 49.937637598827635
Epoch 2080/10000, Loss: 49.95803386033183
Epoch 2090/10000, Loss: 49.95293479174476
Epoch 2100/10000, Loss: 49.96058340104742
Epoch 2110/10000, Loss: 49.95293479174476
Epoch 2120/10000, Loss: 49.955484332460344
Epoch 2130/10000, Loss: 49.96823199750598
Epoch 2140/10000, Loss: 49.95293479174476
Epoch 2150/10000, Loss: 49.96058340104742
Epoch 2160/10000, Loss: 49.95038526387327
Epoch 2170/10000, Loss: 49.980979662551626
Epoch 2180/10000, Loss: 49.965682469634494
Epoch 2190/10000, Loss: 49.96313292891891
Epoch 2200/10000, Loss: 49.96058340104742
Epoch 2210/10000, Loss: 49.965682469634494
Epoch 2220/10000, Loss: 49.95293479174476
Epoch 2230/10000, Loss: 49.96823199750598
Epoch 2240/10000, Loss: 49.96313292891891
Epoch 2250/10000, Loss: 49.96823199750598
Epoch 2260/10000, Loss: 49.965682469634494
Epoch 2270/10000, Loss: 49.955484332460344
Epoch 2280/10000, Loss: 49.94783572315768
Epoch 2290/10000, Loss: 49.95038526387327
Epoch 2300/10000, Loss: 49.94018712669912
Epoch 2310/10000, Loss: 49.94783572315768
Epoch 2320/10000, Loss: 49.96313292891891
Epoch 2330/10000, Loss: 49.96823199750598

In [ ]:

# Previsões
with torch.no_grad():
    predictions = model(X_test)
    predicted_labels = (predictions >= 0.5).squeeze().int()

# Exibindo as previsões
for pred in predicted_labels:
    print("Evento" if pred == 1 else "Não evento")